import prettier from 'eslint-config-prettier';
import path from 'node:path';
import js from '@eslint/js';
import svelte from 'eslint-plugin-svelte';
import { defineConfig, includeIgnoreFile } from 'eslint/config';
import globals from 'globals';
import ts from 'typescript-eslint';

const gitignorePath = path.resolve(import.meta.dirname, '.gitignore');

export default defineConfig(
	includeIgnoreFile(gitignorePath),
	// Generated by `npm run db:types` — not our code to lint.
	{ ignores: ['src/lib/types/database.ts'] },
	js.configs.recommended,
	ts.configs.recommended,
	svelte.configs.recommended,
	prettier,
	svelte.configs.prettier,
	{
		languageOptions: { globals: { ...globals.browser, ...globals.node } },
		rules: {
			// typescript-eslint strongly recommend that you do not use the no-undef lint rule on TypeScript projects.
			// see: https://typescript-eslint.io/troubleshooting/faqs/eslint/#i-get-errors-from-the-no-undef-rule-about-global-variables-not-being-defined-even-though-there-are-no-typescript-errors
			'no-undef': 'off'
		}
	},
	{
		files: ['**/*.svelte', '**/*.svelte.ts', '**/*.svelte.js'],
		languageOptions: {
			parserOptions: {
				projectService: true,
				extraFileExtensions: ['.svelte'],
				parser: ts.parser
			}
		}
	},
	{
		rules: {
			// This app deploys at the domain root (no SvelteKit `paths.base`), so plain
			// internal hrefs like href="/login" are safe. Disable the resolve()
			// requirement to keep links readable; re-enable if a base path is added.
			'svelte/no-navigation-without-resolve': 'off'
		}
	},
	{
		// Layouts load on every page in their subtree (the root layout on ALL pages).
		// Importing the `$lib/components` barrel here drags every re-exported component
		// (ListingForm, ImageUploader, …) into that always-loaded bundle and slows
		// hydration — the Section 10 regression. Import components DIRECTLY in layouts.
		files: ['src/routes/**/+layout.svelte', 'src/routes/**/+layout.{ts,js}'],
		rules: {
			'no-restricted-imports': [
				'error',
				{
					paths: [
						{
							name: '$lib/components',
							message:
								'Import components directly in layouts (e.g. $lib/components/SearchBar.svelte) to keep the every-page bundle lean.'
						}
					]
				}
			]
		}
	}
);
