import { createHmac, timingSafeEqual } from 'node:crypto';
import { env as dynamicEnv } from '$env/dynamic/private';
import { env } from '$lib/server/env';

/**
 * ⚠️ SERVER-ONLY. A thin, typed Paystack client with exactly three capabilities:
 * initialize a transaction, verify one, and verify a webhook signature. Nothing
 * else belongs here — this module is the single place the app talks to Paystack.
 *
 * It lives under `src/lib/server/` and reads a private env var, so SvelteKit
 * blocks it from client bundles at build time. The secret key must never reach
 * the browser; note that D2's redirect flow means the PUBLIC key isn't used at
 * all — there is no inline popup, so nothing Paystack-related ships to the client.
 */

/** Every amount crossing this boundary is integer minor units (KES cents), per D8. */
export const PAYSTACK_CURRENCY = 'KES' as const;

/**
 * Paystack's documented `channels` identifiers are:
 *   card, bank, apple_pay, ussd, qr, mobile_money, bank_transfer, eft,
 *   capitec_pay, payattitude
 * M-Pesa in Kenya is reached through `mobile_money` — `mpesa` is the *provider*
 * code one level down (used when charging directly), NOT a channel identifier.
 */
export const PAYSTACK_CHANNELS = ['mobile_money', 'card'] as const;
export type PaystackChannel = (typeof PAYSTACK_CHANNELS)[number];

const PAYSTACK_API_BASE = 'https://api.paystack.co';

export interface InitializeParams {
	email: string;
	/** Integer KES cents (D8). */
	amountCents: number;
	/** Our reference (`msk_…`), generated by us and unique-indexed (D10). */
	reference: string;
	callbackUrl: string;
	channels?: readonly PaystackChannel[];
}

export interface InitializeResult {
	authorizationUrl: string;
	accessCode: string;
	reference: string;
}

/**
 * A normalised verify response. `raw` carries the untouched Paystack body — the
 * payments audit trail stores that verbatim (D9), so nothing is lost to
 * normalisation.
 */
export interface VerifyResult {
	/** Paystack transaction status: success | failed | abandoned | ongoing | pending | reversed. */
	status: string;
	reference: string;
	/** Integer minor units as Paystack reported them. */
	amountCents: number;
	currency: string;
	raw: unknown;
}

export interface PaystackClient {
	initializeTransaction(params: InitializeParams): Promise<InitializeResult>;
	verifyTransaction(reference: string): Promise<VerifyResult>;
	/** Pure and synchronous — never throws, whatever the header contains. */
	verifyWebhookSignature(rawBody: string, signatureHeader: string | null | undefined): boolean;
}

/**
 * R-4: the two test-only variables are read through `$env/dynamic/private` so no
 * Vercel scope gains a build-time requirement — they are deliberately absent
 * from the static schema in `env.ts`. The `process.env` fallback covers runtimes
 * where the virtual module snapshots at import time (Vitest, one-off scripts).
 */
function readRuntimeEnv(name: string): string | undefined {
	return dynamicEnv[name] ?? process.env[name];
}

function assertIntegerCents(amountCents: number): void {
	if (!Number.isSafeInteger(amountCents) || amountCents <= 0) {
		throw new Error(
			`Paystack amount must be a positive integer of minor units (cents); got ${amountCents}. ` +
				`Money is integer cents end to end (D8) — never a float.`
		);
	}
}

/**
 * HMAC-SHA512 of the RAW body, compared to the header in constant time.
 *
 * Shared by both implementations on purpose: the dev mock-pay page posts a
 * genuinely-signed body to our own webhook, so the mock must verify exactly as
 * production does. Only the network calls are faked, never the crypto.
 */
function verifySignature(
	secretKey: string,
	rawBody: string,
	signatureHeader: string | null | undefined
): boolean {
	if (!signatureHeader) return false;

	const expected = createHmac('sha512', secretKey).update(rawBody, 'utf8').digest('hex');

	// timingSafeEqual THROWS when the buffers differ in length, so a malformed or
	// truncated header would crash the webhook handler. Compare lengths first and
	// bail — the length of a signature is not a secret, so this leaks nothing.
	if (signatureHeader.length !== expected.length) return false;

	try {
		return timingSafeEqual(Buffer.from(expected, 'utf8'), Buffer.from(signatureHeader, 'utf8'));
	} catch {
		return false;
	}
}

/** The real thing. `fetchImpl` is injectable so tests can assert request shaping. */
export class RealPaystackClient implements PaystackClient {
	constructor(
		private readonly secretKey: string,
		private readonly fetchImpl: typeof fetch = fetch
	) {
		if (!secretKey.trim()) {
			throw new Error(
				'PAYSTACK_SECRET_KEY is missing. Add it to .env (see .env.example); in Vercel it lives ' +
					'in the project Environment Variables.'
			);
		}
	}

	private async request(path: string, init?: RequestInit): Promise<Record<string, unknown>> {
		const response = await this.fetchImpl(`${PAYSTACK_API_BASE}${path}`, {
			...init,
			headers: {
				Authorization: `Bearer ${this.secretKey}`,
				'Content-Type': 'application/json',
				...(init?.headers ?? {})
			}
		});

		const body = (await response.json()) as Record<string, unknown>;
		if (!response.ok || body.status !== true) {
			throw new Error(
				`Paystack ${path} failed (HTTP ${response.status}): ${String(body.message ?? 'unknown error')}`
			);
		}
		return body;
	}

	async initializeTransaction(params: InitializeParams): Promise<InitializeResult> {
		assertIntegerCents(params.amountCents);

		const body = await this.request('/transaction/initialize', {
			method: 'POST',
			body: JSON.stringify({
				email: params.email,
				amount: params.amountCents,
				currency: PAYSTACK_CURRENCY,
				reference: params.reference,
				callback_url: params.callbackUrl,
				channels: params.channels ?? PAYSTACK_CHANNELS
			})
		});

		const data = (body.data ?? {}) as Record<string, unknown>;
		return {
			authorizationUrl: String(data.authorization_url ?? ''),
			accessCode: String(data.access_code ?? ''),
			reference: String(data.reference ?? params.reference)
		};
	}

	async verifyTransaction(reference: string): Promise<VerifyResult> {
		const body = await this.request(`/transaction/verify/${encodeURIComponent(reference)}`, {
			method: 'GET'
		});

		const data = (body.data ?? {}) as Record<string, unknown>;
		return {
			status: String(data.status ?? ''),
			reference: String(data.reference ?? reference),
			amountCents: Number(data.amount ?? 0),
			currency: String(data.currency ?? ''),
			raw: body
		};
	}

	verifyWebhookSignature(rawBody: string, signatureHeader: string | null | undefined): boolean {
		return verifySignature(this.secretKey, rawBody, signatureHeader);
	}
}

/** What a test (or the dev mock-pay page) seeds for a reference. */
export interface SeededVerify {
	status: string;
	amountCents: number;
	currency?: string;
}

/**
 * Local/test double. Makes no network calls: initialize returns a deterministic
 * URL pointing at the dev mock-pay route, and verify answers from an in-memory
 * registry that tests and the mock-pay page seed.
 *
 * Signature verification is NOT faked — see verifySignature above.
 */
export class MockPaystackClient implements PaystackClient {
	private readonly registry = new Map<string, SeededVerify>();

	constructor(
		private readonly secretKey: string,
		private readonly appUrl: string
	) {}

	/** Seed the verify response for a reference. */
	seedVerify(reference: string, result: SeededVerify): void {
		this.registry.set(reference, result);
	}

	clearRegistry(): void {
		this.registry.clear();
	}

	async initializeTransaction(params: InitializeParams): Promise<InitializeResult> {
		assertIntegerCents(params.amountCents);
		const url = new URL('/dev/mock-pay', this.appUrl);
		url.searchParams.set('reference', params.reference);
		return {
			authorizationUrl: url.toString(),
			accessCode: `mock_access_${params.reference}`,
			reference: params.reference
		};
	}

	async verifyTransaction(reference: string): Promise<VerifyResult> {
		const seeded = this.registry.get(reference);
		// Unseeded references read as still-pending, so the callback page's
		// in-progress state is exercisable without special-casing the mock.
		const status = seeded?.status ?? 'pending';
		const amountCents = seeded?.amountCents ?? 0;
		const currency = seeded?.currency ?? PAYSTACK_CURRENCY;

		return {
			status,
			reference,
			amountCents,
			currency,
			raw: {
				status: true,
				message: 'Verification successful',
				data: { status, reference, amount: amountCents, currency, mock: true }
			}
		};
	}

	verifyWebhookSignature(rawBody: string, signatureHeader: string | null | undefined): boolean {
		return verifySignature(this.secretKey, rawBody, signatureHeader);
	}

	/**
	 * Sign a body the way Paystack would. Only the mock has this: the dev mock-pay
	 * page uses it to post a GENUINELY signed webhook to our own endpoint, so the
	 * local flow exercises the real verification path instead of bypassing it.
	 */
	signAsPaystack(rawBody: string): string {
		return createHmac('sha512', this.secretKey).update(rawBody, 'utf8').digest('hex');
	}
}

/**
 * Which implementation a given environment selects — pure, so it is exhaustively
 * testable without touching real env or constructing a client.
 *
 * PAYSTACK_MOCK must NEVER be set in any Vercel environment: the mock accepts
 * fabricated payments, so a deployed tier running it would treat an unpaid order
 * as paid. This turns that from a convention into a hard startup failure.
 * Section 11's checklist separately asserts the variable is absent from every
 * Vercel scope.
 */
export function resolvePaystackClientKind(source: {
	PAYSTACK_MOCK?: string;
	VERCEL?: string;
}): 'mock' | 'real' {
	// Exactly '1' — no truthiness, so a stray "true"/"0" can't enable the mock.
	const mockRequested = source.PAYSTACK_MOCK === '1';

	if (mockRequested && source.VERCEL) {
		throw new Error(
			'PAYSTACK_MOCK=1 detected in a Vercel environment. The mock client accepts ' +
				'fabricated payments and must never run on a deployed tier. Remove PAYSTACK_MOCK ' +
				'from this environment immediately.'
		);
	}

	return mockRequested ? 'mock' : 'real';
}

/** True only when PAYSTACK_MOCK is explicitly '1'. */
export function isPaystackMockEnabled(): boolean {
	return readRuntimeEnv('PAYSTACK_MOCK') === '1';
}

let mockSingleton: MockPaystackClient | null = null;

/** The only way app code should obtain a client. */
export function getPaystackClient(): PaystackClient {
	const kind = resolvePaystackClientKind({
		PAYSTACK_MOCK: readRuntimeEnv('PAYSTACK_MOCK'),
		VERCEL: readRuntimeEnv('VERCEL')
	});

	const secretKey = env.PAYSTACK_SECRET_KEY ?? '';

	if (kind === 'mock') {
		// Memoised: the verify registry is shared state across requests.
		mockSingleton ??= new MockPaystackClient(secretKey, env.PUBLIC_APP_URL);
		return mockSingleton;
	}

	return new RealPaystackClient(secretKey);
}

/** Test/dev helper: the live mock instance, for seeding. Throws if the mock is off. */
export function getMockPaystackClient(): MockPaystackClient {
	const client = getPaystackClient();
	if (!(client instanceof MockPaystackClient)) {
		throw new Error('The mock Paystack client is only available when PAYSTACK_MOCK=1.');
	}
	return client;
}
