import { createHmac, timingSafeEqual } from 'node:crypto';
import { env } from '$lib/server/env';
import { readRuntimeEnv } from '$lib/server/runtime-env';

/**
 * ⚠️ SERVER-ONLY. A thin, typed Paystack client with exactly three capabilities:
 * initialize a transaction, verify one, and verify a webhook signature. Nothing
 * else belongs here — this module is the single place the app talks to Paystack.
 *
 * It lives under `src/lib/server/` and reads a private env var, so SvelteKit
 * blocks it from client bundles at build time. The secret key must never reach
 * the browser; note that D2's redirect flow means the PUBLIC key isn't used at
 * all — there is no inline popup, so nothing Paystack-related ships to the client.
 */

/** Every amount crossing this boundary is integer minor units (KES cents), per D8. */
export const PAYSTACK_CURRENCY = 'KES' as const;

/**
 * Paystack's documented `channels` identifiers are:
 *   card, bank, apple_pay, ussd, qr, mobile_money, bank_transfer, eft,
 *   capitec_pay, payattitude
 * M-Pesa in Kenya is reached through `mobile_money` — `mpesa` is the *provider*
 * code one level down (used when charging directly), NOT a channel identifier.
 */
export const PAYSTACK_CHANNELS = ['mobile_money', 'card'] as const;
export type PaystackChannel = (typeof PAYSTACK_CHANNELS)[number];

const PAYSTACK_API_BASE = 'https://api.paystack.co';

export interface InitializeParams {
	email: string;
	/** Integer KES cents (D8). */
	amountCents: number;
	/** Our reference (`msk_…` for orders, `boost_…` for boosts), generated by us and unique-indexed (D10, BST-14). */
	reference: string;
	callbackUrl: string;
	channels?: readonly PaystackChannel[];
	/**
	 * Passed through to Paystack and shown on the transaction in their dashboard.
	 *
	 * A LABEL ONLY (BST-14). Nothing in this codebase routes, verifies or reconciles
	 * on metadata: the reference namespace is the discriminator, because it is ours,
	 * unique-indexed, and comes back on the verify response. Metadata exists so a
	 * human reading the Paystack dashboard can tell a boost charge from an order
	 * charge without cross-referencing our database. Never read it back in.
	 */
	metadata?: Record<string, unknown>;
}

export interface InitializeResult {
	authorizationUrl: string;
	accessCode: string;
	reference: string;
}

/**
 * A normalised verify response. `raw` carries the untouched Paystack body — the
 * payments audit trail stores that verbatim (D9), so nothing is lost to
 * normalisation.
 */
export interface VerifyResult {
	/** Paystack transaction status: success | failed | abandoned | ongoing | pending | reversed. */
	status: string;
	reference: string;
	/** Integer minor units as Paystack reported them. */
	amountCents: number;
	currency: string;
	raw: unknown;
}

/**
 * Creating a transfer recipient (Payouts PRD — Section 5, P1).
 *
 * `provider` is Paystack's Kenyan mobile-money slug. It is a WIRE VALUE and
 * whatever Paystack's docs specify wins — the project's "Mpesa" prose spelling
 * does not apply to an API parameter.
 */
export interface TransferRecipientParams {
	/** Full MSISDN in international form, e.g. 254712345678. */
	accountNumber: string;
	/** Shown in the Paystack dashboard; the seller's display name. */
	name: string;
	provider?: string;
}

export interface TransferRecipientResult {
	recipientCode: string;
	raw: unknown;
}

/**
 * Initiating a transfer (Payouts PRD — Section 7, P7).
 *
 * AMOUNT UNIT — confirmed against Paystack's Transfer API docs: `amount` is in
 * the currency's SUBUNIT, the same convention as the Transaction API. For KES
 * the subunit is cents, and `payouts.transfer_amount_kes_cents` is already
 * integer KES cents (D8), so the value passes through with NO conversion. The
 * existing `initializeTransaction` above sends `amount: params.amountCents`
 * unconverted for the same reason — this is the project's settled convention,
 * not a new judgement.
 */
export interface TransferParams {
	/** Integer KES cents == Paystack's subunit. Passed through unconverted. */
	amountKesCents: number;
	recipientCode: string;
	/** The payout row's UUID (P7) — the idempotency key. */
	reference: string;
	reason?: string;
}

export interface TransferResult {
	/** Paystack's own transfer identifier, e.g. TRF_xxxxx. */
	transferCode: string;
	/** Paystack's transfer status at initiation: pending | otp | success | failed. */
	status: string;
	raw: unknown;
}

/**
 * A normalised transfer-verify response (Payouts PRD — Section 8, P8).
 *
 * ENDPOINT — confirmed against Paystack's Transfer API docs: `GET
 * /transfer/verify/:reference`, keyed by OUR reference (the payout UUID, P7)
 * rather than by transfer_code. Using our own reference matters: it is the value
 * we control and unique-indexed, so a verify can be performed for any payout row
 * without first having stored anything Paystack gave back.
 */
export interface TransferVerifyResult {
	/** pending | otp | success | failed | reversed | abandoned. */
	status: string;
	reference: string;
	/** Integer minor units as Paystack reported them. */
	amountCents: number;
	currency: string;
	raw: unknown;
}

/**
 * A non-OK response from Paystack, carrying the HTTP status so callers can tell
 * a business-terminal failure from an infrastructure one.
 *
 * This distinction is load-bearing in Section 6: an unknown reference comes back
 * as HTTP 400 ("Transaction reference not found") and must NOT be retried, while
 * a 401, 429 or 5xx must be. Without the status, callers would be reduced to
 * matching on message text.
 */
export class PaystackApiError extends Error {
	constructor(
		readonly status: number,
		readonly paystackMessage: string,
		path: string
	) {
		super(`Paystack ${path} failed (HTTP ${status}): ${paystackMessage}`);
		this.name = 'PaystackApiError';
	}

	/**
	 * True when Paystack is telling us the request itself is not satisfiable —
	 * a reference it has never seen. Retrying cannot change the answer.
	 * 401/403 (bad key) and 429/5xx are deliberately excluded: those are
	 * configuration or availability problems that should retry and stay loud.
	 */
	get isTerminal(): boolean {
		return this.status === 400 || this.status === 404;
	}

	/**
	 * Is Paystack refusing this because the reference has already been used?
	 *
	 * P7 makes the payout UUID the transfer reference precisely so a retry cannot
	 * double-pay: Paystack refuses the second attempt. That refusal means "the
	 * transfer already exists", which for the initiation step is SUCCESS, not
	 * failure — so it must be told apart from a real rejection.
	 *
	 * Message-matched because Paystack does not give duplicates a distinct code;
	 * the wording is checked case-insensitively and covers the phrasings their
	 * transfer endpoint uses for an already-seen reference.
	 */
	get isDuplicateReference(): boolean {
		return /duplicate|already\s+exist|has\s+been\s+used/i.test(this.paystackMessage);
	}
}

export interface PaystackClient {
	initializeTransaction(params: InitializeParams): Promise<InitializeResult>;
	verifyTransaction(reference: string): Promise<VerifyResult>;
	/** Pure and synchronous — never throws, whatever the header contains. */
	verifyWebhookSignature(rawBody: string, signatureHeader: string | null | undefined): boolean;
	/** Payouts Section 5 (P1) — register a seller's Mpesa number as a transfer destination. */
	createTransferRecipient(params: TransferRecipientParams): Promise<TransferRecipientResult>;
	/** Payouts Section 7 (P7) — send money to a registered recipient. */
	initiateTransfer(params: TransferParams): Promise<TransferResult>;
	/** Payouts Section 8 (P8) — the direct verify that must agree before any terminal transition. */
	verifyTransfer(reference: string): Promise<TransferVerifyResult>;
}

/**
 * Paystack's mobile-money provider slug for Kenya. Confirmed against Paystack's
 * Transfers documentation for Kenyan mobile money, where the recipient `type` is
 * `mobile_money` and `bank_code` carries the provider — `MPESA` for Safaricom.
 *
 * A wire value, so it keeps Paystack's own spelling rather than the project's
 * unhyphenated "Mpesa" prose convention. Overridable per call so a docs change
 * does not require a code change in the calling layer.
 */
export const PAYSTACK_MPESA_PROVIDER = 'MPESA' as const;

function assertIntegerCents(amountCents: number): void {
	if (!Number.isSafeInteger(amountCents) || amountCents <= 0) {
		throw new Error(
			`Paystack amount must be a positive integer of minor units (cents); got ${amountCents}. ` +
				`Money is integer cents end to end (D8) — never a float.`
		);
	}
}

/**
 * HMAC-SHA512 of the RAW body, compared to the header in constant time.
 *
 * Shared by both implementations on purpose: the dev mock-pay page posts a
 * genuinely-signed body to our own webhook, so the mock must verify exactly as
 * production does. Only the network calls are faked, never the crypto.
 */
function verifySignature(
	secretKey: string,
	rawBody: string,
	signatureHeader: string | null | undefined
): boolean {
	if (!signatureHeader) return false;

	const expected = createHmac('sha512', secretKey).update(rawBody, 'utf8').digest('hex');

	// timingSafeEqual THROWS when the buffers differ in length, so a malformed or
	// truncated header would crash the webhook handler. Compare lengths first and
	// bail — the length of a signature is not a secret, so this leaks nothing.
	if (signatureHeader.length !== expected.length) return false;

	try {
		return timingSafeEqual(Buffer.from(expected, 'utf8'), Buffer.from(signatureHeader, 'utf8'));
	} catch {
		return false;
	}
}

/** The real thing. `fetchImpl` is injectable so tests can assert request shaping. */
export class RealPaystackClient implements PaystackClient {
	constructor(
		private readonly secretKey: string,
		private readonly fetchImpl: typeof fetch = fetch
	) {
		if (!secretKey.trim()) {
			throw new Error(
				'PAYSTACK_SECRET_KEY is missing. Add it to .env (see .env.example); in Vercel it lives ' +
					'in the project Environment Variables.'
			);
		}
	}

	private async request(path: string, init?: RequestInit): Promise<Record<string, unknown>> {
		const response = await this.fetchImpl(`${PAYSTACK_API_BASE}${path}`, {
			...init,
			headers: {
				Authorization: `Bearer ${this.secretKey}`,
				'Content-Type': 'application/json',
				...(init?.headers ?? {})
			}
		});

		const body = (await response.json().catch(() => ({}))) as Record<string, unknown>;
		if (!response.ok || body.status !== true) {
			throw new PaystackApiError(response.status, String(body.message ?? 'unknown error'), path);
		}
		return body;
	}

	async initializeTransaction(params: InitializeParams): Promise<InitializeResult> {
		assertIntegerCents(params.amountCents);

		const body = await this.request('/transaction/initialize', {
			method: 'POST',
			body: JSON.stringify({
				email: params.email,
				amount: params.amountCents,
				currency: PAYSTACK_CURRENCY,
				reference: params.reference,
				callback_url: params.callbackUrl,
				channels: params.channels ?? PAYSTACK_CHANNELS,
				// Omitted entirely when absent, so an order charge's request body is
				// byte-identical to what it was before boosts existed.
				...(params.metadata ? { metadata: params.metadata } : {})
			})
		});

		const data = (body.data ?? {}) as Record<string, unknown>;
		return {
			authorizationUrl: String(data.authorization_url ?? ''),
			accessCode: String(data.access_code ?? ''),
			reference: String(data.reference ?? params.reference)
		};
	}

	async verifyTransaction(reference: string): Promise<VerifyResult> {
		const body = await this.request(`/transaction/verify/${encodeURIComponent(reference)}`, {
			method: 'GET'
		});

		const data = (body.data ?? {}) as Record<string, unknown>;
		return {
			status: String(data.status ?? ''),
			reference: String(data.reference ?? reference),
			amountCents: Number(data.amount ?? 0),
			currency: String(data.currency ?? ''),
			raw: body
		};
	}

	verifyWebhookSignature(rawBody: string, signatureHeader: string | null | undefined): boolean {
		return verifySignature(this.secretKey, rawBody, signatureHeader);
	}

	async createTransferRecipient(params: TransferRecipientParams): Promise<TransferRecipientResult> {
		const body = await this.request('/transferrecipient', {
			method: 'POST',
			body: JSON.stringify({
				type: 'mobile_money',
				name: params.name,
				account_number: params.accountNumber,
				bank_code: params.provider ?? PAYSTACK_MPESA_PROVIDER,
				currency: PAYSTACK_CURRENCY
			})
		});

		const data = (body.data ?? {}) as Record<string, unknown>;
		return { recipientCode: String(data.recipient_code ?? ''), raw: body };
	}

	async initiateTransfer(params: TransferParams): Promise<TransferResult> {
		// No unit conversion: Paystack's `amount` is the currency subunit, which for
		// KES is cents, and our column is already integer KES cents (D8).
		assertIntegerCents(params.amountKesCents);

		const body = await this.request('/transfer', {
			method: 'POST',
			body: JSON.stringify({
				source: 'balance',
				amount: params.amountKesCents,
				recipient: params.recipientCode,
				reference: params.reference,
				currency: PAYSTACK_CURRENCY,
				reason: params.reason ?? 'MySoko seller payout'
			})
		});

		const data = (body.data ?? {}) as Record<string, unknown>;
		return {
			transferCode: String(data.transfer_code ?? ''),
			status: String(data.status ?? ''),
			raw: body
		};
	}

	async verifyTransfer(reference: string): Promise<TransferVerifyResult> {
		const body = await this.request(`/transfer/verify/${encodeURIComponent(reference)}`, {
			method: 'GET'
		});

		const data = (body.data ?? {}) as Record<string, unknown>;
		return {
			status: String(data.status ?? ''),
			reference: String(data.reference ?? reference),
			amountCents: Number(data.amount ?? 0),
			currency: String(data.currency ?? ''),
			raw: body
		};
	}
}

/** What a test (or the dev mock-pay page) seeds for a reference. */
export interface SeededVerify {
	status: string;
	amountCents: number;
	currency?: string;
}

/**
 * Local/test double. Makes no network calls: initialize returns a deterministic
 * URL pointing at the dev mock-pay route, and verify answers from an in-memory
 * registry that tests and the mock-pay page seed.
 *
 * Signature verification is NOT faked — see verifySignature above.
 */
export class MockPaystackClient implements PaystackClient {
	private readonly registry = new Map<string, SeededVerify>();
	/** References already transferred, so a second attempt behaves like Paystack's. */
	private readonly transfers = new Map<string, string>();
	private readonly transferFailures = new Map<string, { status: number; message: string }>();
	private readonly transferVerifies = new Map<string, SeededVerify>();

	constructor(
		private readonly secretKey: string,
		private readonly appUrl: string
	) {}

	/** Seed the verify response for a reference. */
	seedVerify(reference: string, result: SeededVerify): void {
		this.registry.set(reference, result);
	}

	/**
	 * Make the next `initiateTransfer` for this reference fail, so Section 7's
	 * rejection path is reachable without a network.
	 */
	seedTransferFailure(reference: string, failure: { status: number; message: string }): void {
		this.transferFailures.set(reference, failure);
	}

	/**
	 * Seed what `verifyTransfer` will report for a reference (Section 8, P8).
	 *
	 * The double-verification design only means anything if the verify can
	 * DISAGREE with the webhook, so this is deliberately independent of what
	 * `initiateTransfer` recorded — seed 'failed' against a transfer.success
	 * delivery and the mismatch branch is exercised for real.
	 */
	seedTransferVerify(reference: string, result: SeededVerify): void {
		this.transferVerifies.set(reference, result);
	}

	clearRegistry(): void {
		this.registry.clear();
		this.transfers.clear();
		this.transferFailures.clear();
		this.transferVerifies.clear();
	}

	async initializeTransaction(params: InitializeParams): Promise<InitializeResult> {
		assertIntegerCents(params.amountCents);
		const url = new URL('/dev/mock-pay', this.appUrl);
		url.searchParams.set('reference', params.reference);
		return {
			authorizationUrl: url.toString(),
			accessCode: `mock_access_${params.reference}`,
			reference: params.reference
		};
	}

	async verifyTransaction(reference: string): Promise<VerifyResult> {
		const seeded = this.registry.get(reference);
		// Unseeded references read as still-pending, so the callback page's
		// in-progress state is exercisable without special-casing the mock.
		const status = seeded?.status ?? 'pending';
		const amountCents = seeded?.amountCents ?? 0;
		const currency = seeded?.currency ?? PAYSTACK_CURRENCY;

		return {
			status,
			reference,
			amountCents,
			currency,
			raw: {
				status: true,
				message: 'Verification successful',
				data: { status, reference, amount: amountCents, currency, mock: true }
			}
		};
	}

	verifyWebhookSignature(rawBody: string, signatureHeader: string | null | undefined): boolean {
		return verifySignature(this.secretKey, rawBody, signatureHeader);
	}

	/**
	 * Deterministic recipient code, derived from the number so a re-registration
	 * of the SAME phone is recognisably the same code while a different phone
	 * yields a different one — which is what the replacement spec needs to assert.
	 */
	async createTransferRecipient(params: TransferRecipientParams): Promise<TransferRecipientResult> {
		const recipientCode = `RCP_mock_${params.accountNumber}`;
		return {
			recipientCode,
			raw: {
				status: true,
				message: 'Transfer recipient created successfully',
				data: {
					recipient_code: recipientCode,
					type: 'mobile_money',
					currency: PAYSTACK_CURRENCY,
					mock: true
				}
			}
		};
	}

	/**
	 * Transfers, with Paystack's own idempotency behaviour rather than a stub:
	 * a reference that has already been transferred is REFUSED, exactly as the
	 * real API refuses it. That makes P7's duplicate-reference branch reachable
	 * by simply calling twice, instead of by seeding a fake error.
	 */
	async initiateTransfer(params: TransferParams): Promise<TransferResult> {
		const seeded = this.transferFailures.get(params.reference);
		if (seeded) {
			// One-shot: a retry after a seeded failure should be able to succeed, so
			// the failure does not wedge the reference forever.
			this.transferFailures.delete(params.reference);
			throw new PaystackApiError(seeded.status, seeded.message, '/transfer');
		}

		if (this.transfers.has(params.reference)) {
			throw new PaystackApiError(400, 'Transfer reference is duplicate', '/transfer');
		}

		assertIntegerCents(params.amountKesCents);

		const transferCode = `TRF_mock_${params.reference}`;
		this.transfers.set(params.reference, transferCode);

		return {
			transferCode,
			// Initiation only. Terminal state arrives by webhook + verify (Section 8),
			// never from this call — the mock must not shortcut that.
			status: 'pending',
			raw: {
				status: true,
				message: 'Transfer has been queued',
				data: {
					transfer_code: transferCode,
					reference: params.reference,
					amount: params.amountKesCents,
					currency: PAYSTACK_CURRENCY,
					status: 'pending',
					mock: true
				}
			}
		};
	}

	async verifyTransfer(reference: string): Promise<TransferVerifyResult> {
		const seeded = this.transferVerifies.get(reference);
		// Unseeded references read as still-pending, mirroring verifyTransaction.
		// That is the SAFE default here: 'pending' agrees with no terminal webhook
		// claim, so an un-seeded test can never accidentally transition a payout.
		const status = seeded?.status ?? 'pending';
		const amountCents = seeded?.amountCents ?? 0;
		const currency = seeded?.currency ?? PAYSTACK_CURRENCY;

		return {
			status,
			reference,
			amountCents,
			currency,
			raw: {
				status: true,
				message: 'Transfer retrieved',
				data: { status, reference, amount: amountCents, currency, mock: true }
			}
		};
	}

	/**
	 * Sign a body the way Paystack would. Only the mock has this: the dev mock-pay
	 * page uses it to post a GENUINELY signed webhook to our own endpoint, so the
	 * local flow exercises the real verification path instead of bypassing it.
	 */
	signAsPaystack(rawBody: string): string {
		return createHmac('sha512', this.secretKey).update(rawBody, 'utf8').digest('hex');
	}
}

/**
 * Which implementation a given environment selects — pure, so it is exhaustively
 * testable without touching real env or constructing a client.
 *
 * PAYSTACK_MOCK must NEVER be set in any Vercel environment: the mock accepts
 * fabricated payments, so a deployed tier running it would treat an unpaid order
 * as paid. This turns that from a convention into a hard startup failure.
 * Section 11's checklist separately asserts the variable is absent from every
 * Vercel scope.
 */
export function resolvePaystackClientKind(source: {
	PAYSTACK_MOCK?: string;
	VERCEL?: string;
}): 'mock' | 'real' {
	// Exactly '1' — no truthiness, so a stray "true"/"0" can't enable the mock.
	const mockRequested = source.PAYSTACK_MOCK === '1';

	if (mockRequested && source.VERCEL) {
		throw new Error(
			'PAYSTACK_MOCK=1 detected in a Vercel environment. The mock client accepts ' +
				'fabricated payments and must never run on a deployed tier. Remove PAYSTACK_MOCK ' +
				'from this environment immediately.'
		);
	}

	return mockRequested ? 'mock' : 'real';
}

/** True only when PAYSTACK_MOCK is explicitly '1'. */
export function isPaystackMockEnabled(): boolean {
	return readRuntimeEnv('PAYSTACK_MOCK') === '1';
}

let mockSingleton: MockPaystackClient | null = null;

/** The only way app code should obtain a client. */
export function getPaystackClient(): PaystackClient {
	const kind = resolvePaystackClientKind({
		PAYSTACK_MOCK: readRuntimeEnv('PAYSTACK_MOCK'),
		VERCEL: readRuntimeEnv('VERCEL')
	});

	const secretKey = env.PAYSTACK_SECRET_KEY ?? '';

	if (kind === 'mock') {
		// Memoised: the verify registry is shared state across requests.
		mockSingleton ??= new MockPaystackClient(secretKey, env.PUBLIC_APP_URL);
		return mockSingleton;
	}

	return new RealPaystackClient(secretKey);
}

/** Test/dev helper: the live mock instance, for seeding. Throws if the mock is off. */
export function getMockPaystackClient(): MockPaystackClient {
	const client = getPaystackClient();
	if (!(client instanceof MockPaystackClient)) {
		throw new Error('The mock Paystack client is only available when PAYSTACK_MOCK=1.');
	}
	return client;
}
