-- ============================================================================
-- ADM SCHEMA C — WIDEN THE NOTIFICATION CATALOG
-- (Admin Dashboard PRD — Section 3; rulings ADM-8, ADM-13)
--
-- Four new types join the NTF-2 catalog, named to the existing DOTTED
-- convention (`order.paid`, `boost.expiring_24h`, ...):
--
--   dispute.opened         -> the seller on the disputed order      (ADM-8)
--   dispute.under_review   -> the buyer who opened it               (ADM-8)
--   dispute.resolved       -> buyer AND seller, copy differing by
--                             payload.role                          (ADM-8, ADM-12)
--   listing.removed        -> the seller whose listing was taken down (ADM-13)
--
-- Inngest EVENT names are a separate namespace and are not touched here
-- (`disputes/dispute.opened`, `listings/listing.removed`); these are the
-- catalog values stored in notifications.type.
--
-- NO TypeScript changes in this migration. The union, the four exhaustive
-- consumers, the payload and source-id shapes, the dedupe map, the
-- TRANSACTIONAL set, the TONES map and the four Inngest functions — ten
-- locations across three files — all land in Section 6. This migration only
-- widens what the database will accept, so Section 6 has somewhere to write.
--
-- WHY A DO BLOCK. The constraint is an INLINE, UNNAMED column check
-- (20260811150000:26-35), so its name was generated by Postgres rather than
-- chosen. It is `notifications_type_check` in every environment observed, but
-- that is a naming convention, not a guarantee — so the name is READ from
-- pg_constraint at apply time and never hardcoded. The original migration's own
-- header anticipates this edit exactly (20260811150000:21-25: "A CHECK is
-- edited by a new migration like any other constraint").
--
-- The constraint is re-added under the SAME name it was found with, so this
-- stays discoverable the same way next time — and, as a side effect, it becomes
-- an explicitly named table constraint rather than a generated one.
-- ============================================================================

do $mig$
declare
  v_name text;
  v_def  text;
begin
  -- Find the CHECK constraint that covers the `type` column specifically. Keyed
  -- on conkey rather than on the constraint's text, so an unrelated CHECK added
  -- later cannot be picked up by accident.
  select c.conname, pg_get_constraintdef(c.oid)
    into v_name, v_def
    from pg_constraint c
    join pg_attribute a
      on a.attrelid = c.conrelid
     and a.attnum   = any (c.conkey)
   where c.conrelid = 'public.notifications'::regclass
     and c.contype  = 'c'
     and a.attname  = 'type';

  if v_name is null then
    raise exception
      'ADM-8: no CHECK constraint found on notifications.type — refusing to '
      'guess. Inspect pg_constraint for public.notifications before re-running.';
  end if;

  raise notice 'ADM-8: dropping % -> %', v_name, v_def;

  execute format('alter table public.notifications drop constraint %I', v_name);

  -- Re-added with the FULL value list: the existing seven plus the four new
  -- ones. A CHECK is replaced wholesale, never appended to.
  execute format(
    'alter table public.notifications add constraint %I check (type in (%s))',
    v_name,
    $vals$
      'order.paid',
      'order.completed',
      'payout.sent',
      'review.received',
      'review.response',
      'boost.activated',
      'boost.expiring_24h',
      'dispute.opened',
      'dispute.under_review',
      'dispute.resolved',
      'listing.removed'
    $vals$
  );
end;
$mig$;
